import os.path

Import('root_env')

env = root_env.Clone()
env.Alias("install", env.Install(env["INCLUDEDIR"]))

h_files = \
    [
     "ipset/ipset.h",
    ]

env.Alias("install", env.Install(os.path.join(env["INCLUDEDIR"], "ipset"),
                                 h_files))
