Import('root_env')

env = root_env.Clone()

env.Prepend(CPPPATH=["#/include", ".", "$buddy_CPPPATH"],
            LIBPATH=["$buddy_LIBPATH"])

libipset_files = \
    [
     "general.c",
     "ipv4_set.c",
     "ipv6_set.c",
    ]

libipset = env.SharedLibrary("ipset", libipset_files,
                             LIBS=["$buddy_LIB"])
env.Alias("install", env.Install(env["LIBDIR"], libipset))
Default(libipset)

Export('libipset')
